/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20TokenInterface__factory } from "./ERC20TokenInterface__factory";
export { UpgradeableHYAXRewardsV2__factory } from "./UpgradeableHYAXRewardsV2__factory";
